Repository andela/noldor-ah-frontend, pull requests merged in 2018-12, with the labels that each got.

#5 #161290855 Codeclimate Setup
  .codeclimate.yml
  .eslintrc.json
  .gitignore
  .travis.yml
  README.md
Labels: chore

#8 161290853 Setup React Router Version 4
  src/app.js
  src/components/404.js
  src/components/Home.js
  src/components/Login.js
  src/components/Signup.js
  src/index.js
  src/routes.js
  src/routes/Routes.js
  src/utilities/routePath.js
Labels: done and ready to merge

#6 #161290854 Sass Setup
  .gitignore
  dist/bundle.js
  dist/index.html
  package.json
  src/app.js
  src/static/stylesheets/app.scss
  webpack.config.js
Labels: chore

#17 #161290858 Login Functionality
  .codeclimate.yml
  .eslintrc.json
  .travis.yml
  dist/bundle.js
  dist/index.html
  package.json
  src/App.js
  src/actions/login/loginAction.js
  src/actions/login/tests/loginAction.test.js
  src/actions/notification/notificationAction.js
  src/actions/notification/tests/notificationAction.test.js
  src/actions/simpleAction.js
  src/components/Login.js
  src/components/container/404.js
  src/components/container/Home.js
  src/components/container/Signup.js
  src/components/container/login/Login.js
  src/components/container/login/Login.test.js
  src/components/container/login/__snapshots__/Login.test.js.snap
  src/components/container/login/styles/Login.scss
  src/components/presentational/button/Button.js
  src/components/presentational/button/Button.test.js
  src/components/presentational/button/__snapshots__/Button.test.js.snap
  src/components/presentational/button/styles/Button.scss
  src/components/presentational/index.js
  src/components/presentational/input/Input.js
  src/components/presentational/input/Input.test.js
  src/components/presentational/input/__snapshots__/Input.test.js.snap
  src/components/presentational/input/styles/Input.scss
  src/components/presentational/notification/Notification.js
  src/components/presentational/notification/Notification.test.js
  src/components/presentational/notification/__snapshots__/Notification.test.js.snap
  src/components/presentational/notification/styles/Notification.scss
  src/index.html
  src/index.js
  src/reducers/index.js
  src/reducers/login/loginReducer.js
  src/reducers/login/tests/loginReducer.test.js
  src/reducers/notification/notificationReducer.js
  src/reducers/notification/tests/notificationReducer.test.js
  src/reducers/rootReducer.js
  src/reducers/simpleReducer.js
  src/routes/Routes.js
  src/static/images/login-img.jpg
  src/static/stylesheets/app.scss
  src/store/index.js
  src/tests/App.test.js
  src/types/login.js
  src/types/notification.js
  src/utilities/_variables.scss
  src/utilities/axiosRequest.js
  src/utilities/publicRoute/isLoggedIn.js
  src/utilities/publicRoute/isLoggedIn.test.js
  src/utilities/publicRoute/publicRoute.js
  webpack.config.js
Labels: done and ready to merge, feature

#16 #161290856 User Registration Functionality
  .gitignore
  jest.config.json
  package.json
  src/actions/notificationAction.js
  src/actions/signup/signupAction.js
  src/actions/signup/test/signupAction.test.js
  src/components/container/EmailVerified/EmailVerified.js
  src/components/container/EmailVerified/EmailVerified.test.js
  src/components/container/Signup.js
  src/components/container/Signup/Signup.js
  src/components/container/Signup/Signup.test.js
  src/components/container/Signup/__snapshots__/Signup.test.js.snap
  src/components/container/styles/signup.scss
  src/components/presentational/ModalNotification.js
  src/components/presentational/styles/ModalNotification.scss
  src/components/presentational/styles/Notification.scss
  src/index.html
  src/index.js
  src/reducers/rootReducer.js
  src/reducers/signup/signupReducer.js
  src/reducers/signup/test/signupReducer.test.js
  src/routes/Routes.js
  src/routes/Routes.test.js
  src/static/images/signup_reading.jpg
  src/types/signup.js
  src/utilities/routePath.js
  webpack.config.js
Labels: Conflicts Fixed, done and ready to merge

#21 #161290867 Category List Header
  package.json
  src/components/common/category-list/CategoriesList.test.js
  src/components/common/category-list/CategoryList.js
  src/components/common/category-list/__snapshots__/CategoriesList.test.js.snap
  src/components/container/article/SingleArticle.js
  src/components/container/article/SingleArticle.test.js
  src/components/container/article/__snapshots__/SingleArticle.test.js.snap
  src/components/container/article/style.scss
  src/components/container/home/Home.js
  src/components/container/home/Home.test.js
  src/components/container/home/__snapshots__/Home.test.js.snap
  src/components/container/styles/Home.scss
  src/components/presentational/article/singleArticle.js
  src/components/presentational/article/singleArticle.test.js
  src/components/presentational/category-list/CategoryList.js
  src/components/presentational/home/AllArticles.js
  src/components/presentational/home/FeaturedArticle.js
  src/components/presentational/home/style.scss
  src/components/presentational/index.js
  src/redux/actions/categoriesList/categoriesHeader.js
  src/redux/actions/categoriesList/categoriesHeader.test.js
  src/redux/actions/feature-article/featureArticleAction.test.js
  src/redux/actions/index.js
  src/redux/reducers/categories-list/categoriesList.js
  src/redux/reducers/categories-list/categoriesList.test.js
  src/redux/reducers/rootReducer.js
  src/redux/types/categoriesList.js
Labels: done and ready to merge

#25 #161290873 Search and Filtering Functionality
  src/components/common/header/Header.js
  src/components/common/header/Header.test.js
  src/components/common/styles/footer.scss
  src/components/container/login/Login.js
  src/components/container/search/Search.js
  src/components/container/search/Search.test.js
  src/components/container/styles/Search.scss
  src/components/container/styles/createArticle.scss
  src/components/presentational/search-card/SearchCard.js
  src/components/presentational/search-card/SearchCard.test.js
  src/components/presentational/styles/SearchCard.scss
  src/redux/actions/search/searchAction.js
  src/redux/actions/search/searchAction.test.js
  src/redux/reducers/rootReducer.js
  src/redux/reducers/search/searchReducer.js
  src/redux/reducers/search/searchReducer.test.js
  src/redux/types/search.js
  src/routes/Routes.js
Labels: feature

#28 #162810278 Clear Author Filter by Clicking on a Button
  src/components/container/search/Search.js
  src/components/container/styles/Search.scss
Labels: bug, done and ready to merge
